### PR TITLE
Add file detection to .cyp

### PR DESCRIPTION
**Pull request by austintraver**
https://groups.google.com/forum/#!topic/opencypher/PO5EnspBLs0

https://stackoverflow.com/questions/15161221/neo4j-script-file-format-is-there-any

### CODE REVIEW

**Comment by austintraver** [comment]
@jjaderberg is something preventing this from getting merged? Waiting on you, or someone else with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions)

**Comment by austintraver** [comment]
> @jjaderberg is something preventing this from getting merged? Waiting on you, or someone else with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions)

Checking in one year later... 👀

**Review by jjaderberg — APPROVED** [review]
@austintraver could you update the `How should I use it?` section of the readme as well?

**Comment by simpsonjulian** [comment]
👍

**Comment by austintraver** [comment]
> @austintraver could you update the `How should I use it?` section of the readme as well?

@jjaderberg I noticed you did this on my behalf in https://github.com/neo4j-contrib/cypher-vim-syntax/commit/386abb72a5113dfd3aa88ab59bb1e99d3ff33c8e so thank you for helping bring this across the finish line 🎉

**Pull request merged**
